FROM docker.elastic.co/kibana/kibana:7.17.0

# install https://github.com/johtani/analyze-api-ui-plugin
RUN kibana-plugin install \
    https://github.com/johtani/analyze-api-ui-plugin/releases/download/7.17.0/analyzeApiUi-7.17.0.zip
