FROM node:16.13.2

ARG ALLURECTL=2.3.0

ADD https://github.com/allure-framework/allurectl/releases/download/${ALLURECTL}/allurectl_linux_amd64 /usr/local/bin/allurectl

RUN chmod +x /usr/local/bin/allurectl
