FROM docker.elastic.co/kibana/kibana:8.6.2

# install https://github.com/KazanExpress/analyze-api-ui-plugin
RUN kibana-plugin install \
    https://github.com/KazanExpress/analyze-api-ui-plugin/releases/download/8.6.3/analyzeApiUi-8.6.3.zip
