FROM docker.elastic.co/kibana/kibana:8.6.2

# install https://github.com/johtani/analyze-api-ui-plugin
### commented since the plugin is missing for version 8.6.2 ###
# RUN kibana-plugin install \
#     https://github.com/johtani/analyze-api-ui-plugin/releases/download/7.17.0/analyzeApiUi-7.17.0.zip
