FROM docker.elastic.co/kibana/kibana:7.13.4

# install https://github.com/johtani/analyze-api-ui-plugin
RUN kibana-plugin install \
    https://github.com/johtani/analyze-api-ui-plugin/releases/download/7.13.4/analyzeApiUi-7.13.4.zip
